### ISSUE TITLE
Cannot find module './Node'

### ISSUE THREAD

**Issue by KjartanOli** [jbis9051/HiAPL#2]
I cloned the repository and ran 'npm install' to make sure I had all dependencies. But whenewer I try to run the compiler I get the following error:
```
internal/modules/cjs/loader.js:1034
  throw err;
  ^

Error: Cannot find module './Node'
Require stack:
- /home/kjartan/HiAPL/src/parsers/ast/expression.js
- /home/kjartan/HiAPL/src/parsers/ast/array-expression.js
- /home/kjartan/HiAPL/src/parsers/ast/index.js
- /home/kjartan/HiAPL/src/parsers/HiAPLParser/HiAPLParser.js
- /home/kjartan/HiAPL/src/parsers/HiAPLParser/index.js
- /home/kjartan/HiAPL/src/index.js
- /home/kjartan/HiAPL/bin/hiaplc
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1031:15)
    at Function.Module._load (internal/modules/cjs/loader.js:908:27)
    at Module.require (internal/modules/cjs/loader.js:1091:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/kjartan/HiAPL/src/parsers/ast/expression.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:1202:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1222:10)
    at Module.load (internal/modules/cjs/loader.js:1051:32)
    at Function.Module._load (internal/modules/cjs/loader.js:947:14)
    at Module.require (internal/modules/cjs/loader.js:1091:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/kjartan/HiAPL/src/parsers/ast/expression.js',
    '/home/kjartan/HiAPL/src/parsers/ast/array-expression.js',
    '/home/kjartan/HiAPL/src/parsers/ast/index.js',
    '/home/kjartan/HiAPL/src/parsers/HiAPLParser/HiAPLParser.js',
    '/home/kjartan/HiAPL/src/parsers/HiAPLParser/index.js',
    '/home/kjartan/HiAPL/src/index.js',
    '/home/kjartan/HiAPL/bin/hiaplc'
  ]
}
```

**Comment by jbis9051** [comment]
Ah seems that some places the require is capitalized

**Comment by jbis9051** [comment]
Fixed. Try `git pull` and then `npm install`
